FROM python:3.7-alpine

RUN mkdir -p /app
RUN mkdir -p /app/examples
WORKDIR /app

COPY requirements.txt /app
RUN MULTIDICT_NO_EXTENSIONS=1 YARL_NO_EXTENSIONS=1 pip install -r requirements.txt

COPY examples/api.py /app/examples
COPY examples/server.py /app/examples
COPY examples/server.sh /app/examples
COPY statefun_tasks/ /app/statefun_tasks/

EXPOSE 8005

CMD ["sh", "examples/server.sh"]

